# Generated by Django 4.2.2 on 2023-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('JobID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Skills', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=1000)),
            ],
        ),
    ]
